---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
  labels:
    app: caddy
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: caddy
  labels:
    app: caddy
  annotations:
    io.containers.autoupdate: registry
spec:
  containers:
    - name: caddy
      image: docker.io/caddy:2.10
      volumeMounts:
        - name: caddy-data
          mountPath: /data
        - name: caddy-config
          mountPath: /etc/caddy
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
  volumes:
    - name: caddy-data
      persistentVolumeClaim:
        claimName: caddy-data
    - name: caddy-config
      hostPath:
        path: /usr/local/etc/caddy
        type: Directory
