---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-data
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: immich
  labels:
    app: immich
  annotations:
    io.containers.autoupdate: registry
spec:
  containers:
  - name: redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    annotations:
      io.containers.autoupdate: disabled
  - name: postgresql
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    annotations:
      io.containers.autoupdate: disabled
    env:
    - name: POSTGRES_USER
      value: immich
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: immich-postgresql 
    - name: POSTGRES_DB
      value: immich
    - name: POSTGRES_INITDB_ARGS
      value: --data-checksums
    volumeMounts:
    - name: postgresql-data
      mountPath: /var/lib/postgresql/data
  - name: immich-ml
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumeMounts:
    - name: model-cache
      mountPath: /cache
  - name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    ports:
    - containerPort: 2283
      hostPort: 2283
    env:
    - name: DB_HOSTNAME
      value: localhost
    - name: DB_USERNAME
      value: immich
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: immich-postgresql 
    - name: DB_DATABASE_NAME
      value: immich
    - name: REDIS_HOSTNAME
      value: localhost
    volumeMounts:
    - name: immich-data
      mountPath: /usr/src/app/upload
    - name: localtime
      mountPath: /etc/localtime
    - name: pictures
      mountPath: /mnt/Pictures
      readOnly: true
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
      claimName: immich-postgresql-data
  - name: model-cache
    persistentVolumeClaim:
      claimName: immich-model-cache
  - name: immich-data
    persistentVolumeClaim:
      claimName: immich-data
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File
  - name: pictures
    hostPath:
      path: /var/local/pictures
      type: Directory
