---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgresql-data
  labels:
    app: keycloak
spec:
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    io.containers.autoupdate: registry
spec:
  containers:
  - name: postgresql
    image: docker.io/library/postgres:18.3
    env:
      - name: POSTGRES_USER
        value: keycloak
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: keycloak-postgresql
      - name: POSTGRES_DB
        value: keycloak
      - name: POSTGRES_INITDB_ARGS
        value: --data-checksums
    volumeMounts:
    - name: postgresql-data
      mountPath: /var/lib/postgresql
  - name: keycloak
    image: quay.io/keycloak/keycloak:26.6
    args: ["start"]
    ports:
    - containerPort: 8080
      hostPort: 8080
    env:
      - name: KC_DB
        value: postgres
      - name: KC_DB_URL_HOST
        value: localhost
      - name: KC_DB_URL_DATABASE
        value: keycloak
      - name: KC_DB_USERNAME
        value: keycloak
      - name: KC_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: keycloak-postgresql
      - name: KC_BOOTSTRAP_ADMIN_USERNAME
        value: admin
      - name: KC_BOOTSTRAP_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: keycloak-admin
      - name: KC_HTTP_ENABLED
        value: true
      - name: KC_HEALTH_ENABLED
        value: true
      - name: KC_HOSTNAME
        value: https://login.z3n.dk
      - name: KC_PROXY_HEADERS
        value: xforwarded
  volumes:
  - name: postgresql-data
    persistentVolumeClaim:
      claimName: keycloak-postgresql-data
