* Bootc based server for running container applications

Build and push container image

#+begin_src shell
  podman login https://quay.io/mskoett42
  podman build --pull=newer -t quay.io/mskoett42/bootc-container-server:41 .
  podman push quay.io/mskoett42/bootc-container-server:41
#+end_src

Build installer ISO
#+begin_src shell
  sudo podman pull quay.io/mskoett42/bootc-container-server:41
  sudo podman run \
      --rm \
      -it \
      --privileged \
      --pull=newer \
      --security-opt label=type:unconfined_t \
      -v ./config.toml:/config.toml:ro \
      -v ./output:/output \
      -v /var/lib/containers/storage:/var/lib/containers/storage \
      quay.io/centos-bootc/bootc-image-builder:latest \
      --type anaconda-iso \
      --rootfs xfs \
      quay.io/mskoett42/bootc-container-server:41
#+end_src

** Caddy web server
Caddy's config parser is sensitive to indentation and will fail to start if
something is wrong. The configuration can be validated using:

#+begin_src shell
  podman run --rm -it  -v ${PWD}/:/etc/caddy:Z docker.io/caddy:2.10 caddy validate --config /etc/caddy/Caddyfile
#+end_src

Caddy has a built-in formatter and prettifier for the Caddyfile:

#+begin_src shell
  podman run --rm -it  -v ${PWD}/:/etc/caddy:Z docker.io/caddy:2.10 caddy fmt /etc/caddy/Caddyfile
#+end_src

** Backups
Backup is handled by [[https://torsion.org/borgmatic/][borgmatic]] run daily by a systemd timer. Backups are
configured at an application level in [[file:borgmatic.d/][borgmatic.d]] where each file inherits common settings from [[file:borgmatic-common.yaml][borgmatic-common.yaml]]. All backups go to the same repository, but with different archive names. The archive name is derived from the ~app_name~ constant defined in the application specific configuration.

The repository password is stored in a systemd secret created in this way: ~systemd-ask-password -n | systemd-creds encrypt - /etc/credstore.encrypted/borgmatic.pw~

** Certificates
Cerfificates are managed by [[https://acme.sh/][acme.sh]] which is run on a daily basis by a systemd timer. acme.sh requires some setup before it can be run automatically:

#+begin_src shell
  # Register account. eab-kid and eab-hmac-key can be found on zerossl.com
  podman run --rm -it -v /etc/acme.sh:/acme.sh:Z docker.io/neilpang/acme.sh:latest --register-account --eab-kid <eab-kid> --eab-hmac-key <eab-hmac-key>

  # Auth for simply.com
  export SIMPLY_ApiKey=<api key>
  export SIMPLY_AccountName=<account name>

  # Issue cert for *.z3n.dk
  podman run --rm -it -v /etc/acme.sh:/acme.sh:Z --env=SIMPLY_* docker.io/neilpang/acme.sh:latest --issue --dns dns_simply -d *.z3n.dk
#+end_src
