---
name: Build bootc container image

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.org'
      - '.gitignore'
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: quay.io
  IMAGE_NAME: mskoett42/bootc-container-server
  FEDORA_RELEASE: 44

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-latest

    permissions:
      contents: write # SBOM needs write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.FEDORA_RELEASE }}
          containerfiles: |
            ./Containerfile
      - name: Login to registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FEDORA_RELEASE }}
